Code changes for TM to use latest profiles
Azure-Samples/traffic-manager-ruby-manage-profiles pull request #4
Opened 2017-10-11 20:53 UTC by sarangan12

@vishrutshah @veronicagg @salameer Please review the modified traffic manager sample.

2017-10-11 22:51 UTC, vishrutshah submitted a review, later dismissed
@sarangan12  Changes LGTM! 

Let's wait fro the release and update Gemfile to the released version or meanwhile if we want to push this out, let's update gemfile to point it directly to the `azure-stack` branch.

2017-10-12 01:07 UTC, veronicagg requested changes

2017-10-12 15:05 UTC, devigned reviewed
The module path seems odd. I would have expected `Azure::TrafficManager::Management::Profile_Latest` to be something like `Azure::Profiles::{profile_name}::TrafficManager::Mgmt`. Is the module path this way because it's in the resource provider gem?

2017-10-12 18:25 UTC, devigned submitted a review, later dismissed
```ruby
# Profile API version for Traffic manager
TrafficManagerMgmt = Azure::TrafficManager::Profiles::v2016_09_01::Mgmt
tm_client = TrafficManagerMgmt::Client.new(options)
Models = TrafficManagerMgmt::Models

# Specific API version for TrafficManager
SpecificTM = Azure::TrafficManager::Mgmt::Api_2015_12_31
specific_tm_client = SpecificTM::TrafficManagerClient.new(options)
SpecificModels = SpecificTM::Models

# Usage from the top level azure_sdk rollup gem via a profile
TrafficManagerMgmt = Azure::Profiles::v2016_09_01::TrafficManager::Mgmt
tm_client = TrafficManagerMgmt::Client.new(options)
Models = TrafficManagerMgmt::Models

# Usage from the top level azure_sdk rollup gem via the Latest profile
TrafficManagerMgmt = Azure::Profiles::Latest::TrafficManager::Mgmt
tm_client = TrafficManagerMgmt::Client.new(options)
Models = TrafficManagerMgmt::Models
```

2017-10-12 20:33 UTC, sarangan12 commented on example.rb
> +TrafficManager =  Azure::TrafficManager::Management::Profile_Latest
Changed it to a specific version

2017-10-12 20:34 UTC, sarangan12 commented on example.rb
> +  profile = traffic_manager_client.traffic_manager.profiles.create_or_update(RESOURCE_GROUP_NAME, PROFILE_NAME, param)
No It is not under the client

2017-10-12 20:34 UTC, sarangan12 commented on example.rb
> +  provider = resource_client.resources.providers.register('Microsoft.Network')
No It is not under the client

2017-10-16 20:46 UTC, veronicagg commented
Shouldn't we be updating gem versions at https://github.com/Azure-Samples/traffic-manager-ruby-manage-profiles/blob/28983925d60fcce0a3bed374405552960469f434/Gemfile#L9?

2017-10-16 21:32 UTC, sarangan12 commented
@veronicagg Gemfile has been modified

2017-10-16 22:11 UTC, veronicagg commented
@sarangan12 I think we should wait on merging all the updates to samples, until the gems are released, thanks!

2017-10-16 22:11 UTC, veronicagg approved these changes

2017-10-17 23:17 UTC, merged